# Generated by Django 3.2.23 on 2024-01-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20240124_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Позиция фото'),
        ),
    ]
