# Generated by Django 3.2.23 on 2024-01-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, verbose_name='Долгота'),
        ),
    ]
