# Generated by Django 3.2.23 on 2024-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название'),
        ),
    ]
