# Generated by Django 3.2.23 on 2024-01-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20240129_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
    ]
